import './ts/common/common';
import './ts/common/loaders/preloader';
import './ts/common/detailsModal';
import './ts/helpers/checkingForMovies';
import './ts/library/moviesInMyLibrary';
import './ts/common/pagination/pagination';
import './ts/apiService/moviesAPIService';
import './ts/helpers/scroll/backToTop';
import './ts/firebase/auth/signOut';
